kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "openshift-logforwarding-loki.fullname" . }}
  labels:
    app.kubernetes.io/component: fluentd
{{ include "openshift-logforwarding-loki.labels" . | indent 4 }}