{{- $fullName := include "openshift-logforwarding-loki.fullname" . -}}
{{- $lokiSecret := printf "%s-loki" $fullName -}}
{{- $logForwardingConfig := printf "%s-config" $fullName -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/component: fluentd
{{ include "openshift-logforwarding-loki.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.forwarding.fluentd.replicas }}
  serviceName: {{ $fullName }}-headless
  updateStrategy:
{{ toYaml .Values.forwarding.fluentd.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          name: {{ $fullName }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: fluentd-loglevel
            - name: SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: shared_key
            - name: loki_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: loki-hostname
            - name: loki_SOURCETYPE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: loki-sourcetype
            - name: loki_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: loki-source
            - name: loki_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: loki-port
            - name: loki_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: loki-protocol
            - name: loki_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: loki-insecure
            - name: loki_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: hec-token
            - name: loki_INDEX
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: loki-index
            - name: FLUENTD_SSL_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: fluentd-ssl-passsphrase
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ $logForwardingConfig }}
              readOnly: true
              mountPath: /etc/fluent/
            - mountPath: /secret/fluentd
              name: {{ $fullName }}
              readOnly: true
            - name: buffer
              mountPath: "/var/log/fluentd"
            {{- if and (not .Values.forwarding.loki.insecure) .Values.forwarding.loki.caFile }}
            - mountPath: /secret/loki
              name: loki-certs
              readOnly: true
            {{- end }}
          terminationMessagePolicy: File
          image: {{ .Values.forwarding.fluentd.image }}
          args:
            - scl
            - enable
            - rh-ruby25
            - "--"
            - fluentd
          livenessProbe:
            tcpSocket:
              port: 24224
            periodSeconds: 5
            timeoutSeconds: 3
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 24224
            periodSeconds: 3
            timeoutSeconds: 2
            initialDelaySeconds: 2
          ports:
            - containerPort: 24224
              name: forwarder-tcp
              protocol: TCP
            - containerPort: 24224
              name: forwarder-udp
              protocol: UDP
      serviceAccount: {{ $fullName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ $logForwardingConfig }}
          configMap:
            name: {{ $fullName }}
            items:
              - key: td-agent.conf
                path: fluent.conf
            defaultMode: 420
            optional: true
        - name: {{ $fullName }}
          secret:
            secretName: {{ $fullName }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        {{- if not .Values.forwarding.fluentd.persistence.enabled }}
        - name: buffer
          emptyDir: {}
        {{- end }}
        {{- if and (not .Values.forwarding.loki.insecure) .Values.forwarding.loki.caFile }}
        - name: loki-certs
          secret:
            secretName: {{ $fullName }}-loki
            items:
              - key: loki-ca.crt
                path: loki-ca.crt
        {{- end }}
      dnsPolicy: ClusterFirst
  {{- if .Values.forwarding.fluentd.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: buffer
    spec:
      accessModes:
      - {{ .Values.forwarding.fluentd.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.forwarding.fluentd.persistence.size }}
      {{- if .Values.forwarding.fluentd.persistence.storageClass }}
      {{- if (eq "-" .Values.forwarding.fluentd.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.forwarding.fluentd.persistence.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
