kind: Service
apiVersion: v1
metadata:
  name: {{ template "openshift-logforwarding-loki.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: fluentd
{{ include "openshift-logforwarding-loki.labels" . | indent 4 }}
spec:
  ports:
    - name: 24224-tcp
      protocol: TCP
      port: 24224
      targetPort: 24224
  selector:
    app: {{ template "openshift-logforwarding-loki.fullname" . }}
  clusterIP: None
  sessionAffinity: None
