{{- if and (not .Values.forwarding.loki.insecure) .Values.forwarding.loki.caFile -}}
{{- $lokiCaFile := .Files.Get .Values.forwarding.loki.caFile }}
{{- if not $lokiCaFile -}}
{{- fail "Could not locate loki Certificate" }}
{{ end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openshift-logforwarding-loki.fullname" . }}-loki
  labels:
    app.kubernetes.io/component: loki
{{ include "openshift-logforwarding-loki.labels" . | indent 4 }}
type: Opaque
data:
    loki-ca.crt: {{ $lokiCaFile | b64enc }}
{{ end }}